- include_vars: satosa_vars.yml
  tags: always

- name: Clone satosa-tequila repository
  ansible.builtin.git:
    repo: "{{ satosa_tequila_source_repo }}"
    dest: "{{ satosa_tequila_install_path }}"
    version: "main"
    force: yes
  tags:
    - satosa-tequila

# TODO: use Ansible vars with a template to create this file?
- name: Copy our clients.json to remote
  ansible.builtin.copy:
    src: clients.json
    dest: "{{ satosa_tequila_install_path }}/data/"
  tags:
    - satosa-tequila

- name: Manage the server's certificates
  block:
  - name: Check access to /keybase/team/epfl_satosaaas
    delegate_to: localhost
    ansible.builtin.stat:
      path: /keybase/team/epfl_satosaaas/itsidevfsd0033.xaas.epfl.ch/itsidevfsd0033_xaas_epfl_ch.key
    register: _keybase_mounted
    failed_when: _keybase_mounted.stat.exists is false
    any_errors_fatal: true

  - name: Add the SSL certs
    ansible.builtin.copy:
      content: |
        {{ lookup("pipe", "keybase fs read /keybase/team/epfl_satosaaas/itsidevfsd0033.xaas.epfl.ch/itsidevfsd0033_xaas_epfl_ch.crt")}}
        {{ lookup("pipe", "keybase fs read /keybase/team/epfl_satosaaas/itsidevfsd0033.xaas.epfl.ch/DigiCertCA.crt")}}
      dest: "{{ satosa_tequila_install_path }}/tls/satosa.crt"

  - name: Add the server's private key
    ansible.builtin.copy:
      content: '{{ lookup("pipe", "keybase fs read /keybase/team/epfl_satosaaas/itsidevfsd0033.xaas.epfl.ch/itsidevfsd0033_xaas_epfl_ch.key")}}'
      dest: "{{ satosa_tequila_install_path }}/tls/satosa.key"
  tags:
    - satosa-tequila

# Please see https://github.com/epfl-si/satosa-tequila/blob/main/docker-compose.yml
# from https://github.com/epfl-si/satosa-tequila 
- name: Start the satosa-tequila container
  community.docker.docker_container:
    name: "{{ satosa_tequila_container_name }}"
    image: "{{ satosa_docker_image }}"
    state: started
    restart: true
    command:
      - bash
      - -x
      - /custom-entrypoint.sh
    volumes:
      - "{{ satosa_tequila_install_path }}/custom-entrypoint.sh:/custom-entrypoint.sh:ro"
      - "{{ satosa_tequila_install_path }}/config:/config:ro"
      - "{{ satosa_tequila_install_path }}/config/attributemaps:/attributemaps:ro"
      - "{{ satosa_tequila_install_path }}/data:/data:ro"
      - "{{ satosa_tequila_install_path }}/config/proxy_conf.yaml:/etc/satosa/proxy_conf.yaml:ro"
      - "{{ satosa_tequila_install_path }}/site-python/epfl:/site-python/epfl:ro"
      - "{{ satosa_tequila_install_path }}/tls:/tls:ro"
    env:
      PYTHONPATH: /site-python
      SATOSA_ENTITY_ID: "{{ satosa_entity_id }}"
      SATOSA_BASE_URL: "{{ satosa_base_url }}"
    ports:
     - "443:8443"
  tags:
    - satosa-tequila
